### ISSUE TITLE
Ayecode UI bootstrap design: Click on review is not scrolling to the form

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/geodirectory#1469]
https://secure.helpscout.net/conversation/1339605441/10559?folderId=3812058

#1. Before switching to bootstrap, when I pushed on the "write a review" button, it immediately got me to the bottom of the page for the user to login in order to leave a review. Now when I push the same button it gets me to the first review on the top and the user has to scroll down a lot to register and leave a review.

https://thebeautyadviser.com/saloane/saloane-manichiura-pedichiura-victoriei/nailix-studio-bucuresti/#reviews

**Comment by kprajapatii** [comment]
This issue happens when using GeoDirectory 2.1.x with Supreme Directory 2.0.x. We want customer to move AUI Bootstrap style instead of legacy style.

To fix this apply patch on customer's site: 

In file \themes\supreme-directory\inc\geodirectory-compatibility.php 

Find:
`jQuery(".geodir-tab-head [href='#reviews']")[0].click();`

Replace with:
           `if (jQuery(".geodir-tab-head [href='#reviews']").length) {
                jQuery(".geodir-tab-head [href='#reviews']").trigger('click'); /* AUI */
            } else {
                jQuery('.geodir-tab-head [data-tab="#reviews"]').closest('dd').trigger('click');
            }`

Thanks
