### ISSUE TITLE
Make address optional (discussion)

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#1560]
This has been requested multiple times, let's discuss how it would work.  I think things we need to cover are:

1. If zero address info, where do the listings show exactly?
2. If no exact GPS info but has all other info, what happens with near search?

**Comment by Guust-Flater** [comment]
3. What about users that want to add city and region but not street address?
Will it be complete address or nothing, or is it possible to just leave street address blank?

1. If zero address, they get added to a "No-address" location, with lat 0 and lng 0.
Every listing with 0 0 as coordinates will not display a map on detail, and will have no marker on maps.
GD Listings to have option to display listings with 0 0 coordinates: yes/no

Just thinking ....

**Comment by Stiofan** [comment]
3. the idea is to make all the fields optional. So you could state you are located in London but have no street address or GPS.

**Comment by alexrollin** [comment]
Top requested feature since advent of covid - more directories needed - more business owners need to control visits


Nice to have -

Listings with partial info still show in location queries
 - Examples for region is set without city
  - gd listings if region is set will show
  - on IN search for region
  - region location page

Need to have?

 - post map automatically disabled
 - post map default tab automatically hidden
 - permalinks handling for %city% - error detection? if user enables partial address and city not required, throw error notification for %city% in permalinks?
 - changes to import validation - geolocation not possible without all address info - and nice to have import for incomplete data. less breakage all around!

Additional nice to have

we do have regular requests for service areas, too - https://github.com/AyeCode/geodirectory/issues/1556

**Comment by alexrollin** [comment]
Qs
1. If zero address info, where do the listings show exactly?
2. If no exact GPS info but has all other info, what happens with near search?
3. What about users that want to add city and region but not street address? Will it be complete address or nothing, or is it possible to just leave street address blank?
4. If zero address, they get added to a "No-address" location, with lat 0 and lng 0.
Every listing with 0 0 as coordinates will not display a map on detail, and will have no marker on maps.
GD Listings to have option to display listings with 0 0 coordinates: yes/no

My As
1. Some sort of no location archive, as in #4. Should there be an option to set the 'title' of the no location 'city' ? And other meta fields?
2. Near search should not include any item without a complete address - needs both lat and lon, street, city, region, and country.
3. If all fields are optional, then they are individually optional.
4. GD Post Map has to be updated to display:none when either lat or lon is 0.

**Comment by alexrollin** [comment]
I don't add notes about this, but people request this regularly, like, eveyr couple days.

https://secure.helpscout.net/conversation/1581859560/22422/

**Comment by Stiofan** [comment]
This in it's basic form has been implemented, and will be in the next release, lets close this and get user feedback for further improvements.
