### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/geodirectory#165]
Can @Guust-Flater and @alexrollin please work together to start making GDv2 docs?
Please ask any questions here.

**Comment by alexrollin** [comment]
Yes!

I will ask @Guust-Flater to add in his magic CSS to the new site.

Here is an article rewritten for moving into the new site.

Old format: https://wpgeodirectory.com/docs/translation/

New format (needs magic): https://wpgeodirectory.com/docs-v2/docs/translation/overview/

CSS Issues:

table clear (so text doesn't wrap)
list item trailing space
anchor highlighting

**Comment by pol76** [comment]
CSS thing has been fixed. Let meknow if you see anything else wrong.
Thanks

**Comment by DirkJahn** [comment]
??? I have checked the docu of V2 and I'm really wondering, that this issue here is closed. If it was only a working template for the docu, then please rename the issue, but the mentioned docu is not a docu that is needed to work with the plugin.

**Comment by Guust-Flater** [comment]
I don't think I understand, Dirk. This is a topic for the GD team to get the V2 documentation started, which has happened. Can you clarify your question?

**Comment by DirkJahn** [comment]
I think I have a different understanding of an issue/bug tracking system.
My understanding:
issues/bugs are closed when they are verified resolved. Or the open issue is done.
An issue is never a starting point for me. In this example, the issue cannot be "start with the documentation". It should be "documentation finished" and unless it is really done this issue should kept open.
The goal of an issue tracker is not to have as few open issue as possible. It should show what needs to be fixed or what needs to be done.

As this issue is titled with "Documentation" my expectation here is that the documentation is done. But what I see, and Guust you already agreed, this is a starting point. My question here is to get a documentation, so testing will be easier. I had it many times, that my expectation of a function is different. Without a documentation I only can assume what it might do or not do.
