### ISSUE TITLE
Jobs Directory Demo

### ISSUE THREAD

**Issue by basantaux** [AyeCode/geodirectory#1708]
Please find links for both the demo. 
https://demos.ayecode.io/elementor-jobs-directory/
https://demos.ayecode.io/kadence-jobs-directory/

**Comment by basantaux** [comment]
All The issue has been resolved for the both of the demos
...............................

1 zindex problem for autocompleter in search and archive pages
2 move pins on the map for each listing, so that they are not all over the exact same point
3 job reviews? @stiofan what do you think, I'm not sure we should leave those
4 we should add salary field
5 we should add a field to show how old is the listing
6 apply for the job should open contact form
7 we should add "Location: Remote" badge for remote jobs
8 archive page of elementor looks a lot better than kadence, please try to make them equal
9 remove events CPT from both demos (after a search you can see events option in CPT to search)
10 mobile cards for Elementor much better than Kadence, please try to make them look as similar as possible.

**Comment by laranz** [comment]
[Elementor]

- [ ] [Suggestion] Maybe add a more premium look font and more white space like this? https://landkit.goodthemes.co/ for example this area https://user-images.githubusercontent.com/208945/121137487-4ed01580-c854-11eb-9622-5080315c033b.png
- [ ] the heading font-size for the job title is low? Maybe increase a little bit, so that it emphasize on the page either in home or listing?
- [ ] I searched "PHP" but it also displays Ruby on Rails, Angular & .NET jobs, is this a bug from Geo Search? https://demos.ayecode.io/elementor-jobs-directory/search/?geodir_search=1&stype=gd_jobs&s=PHP&snear=&sgeo_lat=&sgeo_lon=
- [ ] Remove "Google maps" and enable "OSM"? So that the maps display just fine. Now it displays like this https://user-images.githubusercontent.com/208945/121138311-2e548b00-c855-11eb-8634-c3f683a06cfd.png
- [ ] Maybe give different address? https://demos.ayecode.io/elementor-jobs-directory/gd-jobs/ or enable location manager to display jobs on multiple countries,
- [ ] Maybe create another page like this https://landkit.goodthemes.co/careers.html it displays jobs based on category, like it has a Design heading, and displays just design jobs. We can do that using our gd_listing shortcode to just display some category, this way we can showcase this type of things are possible with Geo.
- [ ] Maybe include our addon "Pricing Manager" in this demo? So that the user have different pricing to post job on the site. 
- [ ] Showcase some grid view on the home page like this? https://user-images.githubusercontent.com/208945/121139999-02d2a000-c857-11eb-947d-599fc9274570.png got it from here: https://htmlstream.com/front/demo-jobs/index.html
- [ ] We can also incorporate "advanced search addon" on this demo, so that the user can search like number of years experience, depends on salary, remote or on particular location, "Distance" like some 50miles around him, etc.,
- [ ] [iPhone] hamburger icon not center? https://user-images.githubusercontent.com/208945/121149919-b0967c80-c860-11eb-941b-05c41d64fdad.png
- [ ] [iPhone] Remove this margin/space on mobile devices? https://user-images.githubusercontent.com/208945/121150233-f7847200-c860-11eb-93b0-c8eba24dd704.png
- [ ] For now this two display same content, https://user-images.githubusercontent.com/208945/121150425-26024d00-c861-11eb-89e7-9c4755d40c7c.png maybe we distinguish these details? Maybe in the "Details" we can change it to "Perks" and add details like dental insurance, paid leave, vacation, company retreats, company laptop like that? Add a custom field for perks in the backend perhaps.
- [ ] 




## [ Nicety for a Job demo ]
- [ ] Maybe adding some Popular search terms like this, https://user-images.githubusercontent.com/208945/121145868-00734480-c85d-11eb-8164-cedac681f28c.png just some static HTML predefined search links.
- [ ] Maybe something like this the job count? https://user-images.githubusercontent.com/208945/121146338-7677ab80-c85d-11eb-82fc-3c965d1fedb4.png
- [ ] Maybe something like this https://user-images.githubusercontent.com/208945/121149059-f43cb680-c85f-11eb-8100-c076cc99682b.png we jobs by skills like display gd_catgories, jobs by locations display locations using location manager, roles I don't know, maybe display "tag cloud"?

**Comment by basantaux** [comment]
@laranz there is some changes to content and layout for the both of the demo. also fixed the issues.
Please check when you have time.
