### ISSUE TITLE
Doc for custom fields options

### ISSUE THREAD

**Issue by pol76** [AyeCode/geodirectory#1782]
Hi Sufyan,

hope you are doing great.

We need a doc explaining how to add options into custom fields.

For example, for select fields this is how you add options with a placeholder:

Select Status/,Unfurnished,Furnished,Partially furnished,Optional

This is not really self-explanatory, so we need to have clear instructions. We need this for every field where users can add options, if you have doubts please ask to Stiofan and Kiran to provide an example for each. 

This is kinda urgent.

Thanks,

**Comment by pol76** [comment]
p.s. I myself couldn't find how to do it and had to dig in our demos, which isn't really something a user can do...

**Comment by kprajapatii** [comment]
- Option Values should be separated by comma.
- If using for a "tick filter" place a / and then either a 1 for true or 0 for false. eg: "No Dogs Allowed/0,Dogs Allowed/1" (Select only, not multiselect)
- If using OPTGROUP tag to grouping options, use "{optgroup}OPTGROUP-LABEL|OPTION-1,OPTION-2{/optgroup}"

**Comment by alexrollin** [comment]
this info is available in the tooltip for the options in the custom field settings.

**Comment by pol76** [comment]
The info on the tooltip is extremely confusing. Nowhere I could find something like this: 

Select Status/,Unfurnished,Furnished,Partially furnished,Optional

Had to go check the docs

**Comment by sufyanism** [comment]
Hi 
This - https://docs.wpgeodirectory.com/article/593-custom-fields

**Comment by alexrollin** [comment]
I reviewed the doc

---------------------------------------------------------

The section about optgroups needs an example with 2 optgroups. I recommend colors and numbers.

Opt groups are for multiple groups of options, grouped by different Placeholders. 

In this example with a single group of options, the label is "OPTGROUP-LABEL" and all the options are grouped under that label.

{optgroup}OPTGROUP-LABEL|OPTION-1,OPTION-2{/optgroup}". 

Here is an example of 2 optgroups, the first with the label "Colors" and the second with the label "Numbers".

{optgroup}Colors|Red,Orange,Yellow/#FFFF00,Green,Blue{/optgroup}{optgroup}Numbers|1,2,3,4,5{/optgroup}

---------------------------------------------------------

There should be a small section about the **'Database Value"**

When specifying options, you can also specify the database value that will be saved.

For example, maybe you want to save the RGB Hex value of a color, instead of the name. You could do that by speciying the name of the color as the label, then the value to be saved as the hex color like this

Red/FF0000,Orange/FFA500,Yellow/FFFF00,Green/00FF00,Blue/0000FF

So, with options set this way, when the user select Yellow, then FFFF00 is saved in the database.

If you do not specify text, then the label will be cleaned up and then stored. The value that is saved will be stored without capital letters, and leading spaces will be removed. "   Yellow" will be stored as "yellow".

---------------------------------------------------------

The section for multiselect should show a multiselect on the output like

![image](https://user-images.githubusercontent.com/114659/123437704-4146b980-d5d0-11eb-98cb-c596b2865ecc.png)
(https://ppldb.com/v2/wp-admin/post-new.php?post_type=gd_event)
