### ISSUE TITLE
Feedback/issues for Conditional Fields

### ISSUE THREAD

**Issue by kprajapatii** [AyeCode/geodirectory#1874]

**Comment by laranz** [comment]
- [ ] if we hide the required field on condition, then there is no error message, also the form is not submiting.

- [ ]  If the condition is set on a custom field, can we always open the "Conditional Fields" when we open that particular field? https://take.ms/MoNCg

- [ ] This is the setting I choose on description field. "hide" -> "Title" -> "Contains" and type "test" in the condition. Now when I type test in the title it hides the description, but when I type "this is a test" it didn't hide the description.

- [ ] **[Enhancement/Suggestion]**  Added a fieldset, and inside that I put Tags, and Description with the condition like this https://take.ms/UczQA but in the frontend, when I type the title "test" it didn't hide the fieldset. If this is by design, we can use this option to remove a couple of fields with the condition, instead hiding the fields separately. 

- [ ] Should we check all conditions after we press "Submit Listings" because now we can easily show/hide the fields by CSS.

**Comment by Stiofan** [comment]
- [ ] If a field has a condition can we add a font awesome eye in the main bar with hover title that reads "has hide conditions"

**Comment by kprajapatii** [comment]
-  if we hide the required field on condition, then there is no error message, also the form is not submiting.
< DONE

-  If the condition is set on a custom field, can we always open the "Conditional Fields" when we open that particular field? https://take.ms/MoNCg
< By default conditional fields minimized like advanced options.

-  This is the setting I choose on description field. "hide" -> "Title" -> "Contains" and type "test" in the condition. Now when I type test in the title it hides the description, but when I type "this is a test" it didn't hide the description.
< DONE

-  [Enhancement/Suggestion] Added a fieldset, and inside that I put Tags, and Description with the condition like this https://take.ms/UczQA but in the frontend, when I type the title "test" it didn't hide the fieldset. If this is by design, we can use this option to remove a couple of fields with the condition, instead hiding the fields separately.
< Fieldset is just title to the group of fields section. Each field has own conditional fields.

- Should we check all conditions after we press "Submit Listings" because now we can easily show/hide the fields by CSS.
< Does not make sense.

- [Suggestions] If we give more than one rule, should we add a OR and AND between the rules?
< We will check in future based on feedback from customers

- If a field has a condition can we add a font awesome eye in the main bar with hover title that reads "has hide conditions"
< DONE
