### ISSUE TITLE
Improve add listing by hiding coordinates

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#2049]
Most members want shorter forms and to remove things they dont want their authors to see.

Coordinates (and the default category) have got to be first on the list.

How can we improve the address field so that users can hide the lat and lon fields that they never want users to use?

It should also be noted that with either map api it is too easy to have bad data in these fields that can break an archive map.

**Comment by alexrollin** [comment]
https://secure.helpscout.net/conversation/1818639014/30356/

**Comment by Stiofan** [comment]
FYI we have options to hide lat/long and map view and also zip.  I do think the settings could make that clearer but also we could improve the general UX of the address input part.

**Comment by alexrollin** [comment]
I wasn't able to recreate the issue. It could be I was looking at someone site who had hidden it with CSS before. This option to hide them 'should' work. Maybe I will come across another one with that issue again and re-visit.

I checked the language used in the settings and I think it could be improved if anyone wants to go in that direction.

**Comment by kprajapatii** [comment]
@alexrollin Default category field should be visible to the user so user can choose one as a default category from the multiple selected categories.

Latitude & longitude values are necessary to function map correctly. We have already settings to hide latitude/longitude from the add listing form. Due to hidden lat/lon we have seen issues that listings saved with empty lat/long and it broken maps. To counter this we have made changes few months back. So when user click to add listing form with hidden and empty latitude/longitude fields then fields will be visible to user asking to enter latitude/longitude manually.

@Stiofan  @pol76

**Comment by alexrollin** [comment]
seems fixed by kiran's changes - yay!
