### ISSUE TITLE
Wizard - Recommended Plugins

### ISSUE THREAD

**Issue by DirkJahn** [AyeCode/geodirectory#211]
UsersWP is nice, but here for me "WP Easy Updates" is missing. The first thing after the wizard is a message that "WP Easy Updates" is required.

My suggestion: Add a category on this page for required plugins and recommended plugins.

![pic70](https://user-images.githubusercontent.com/35274187/38243168-f1fb4cfa-3736-11e8-88c1-9aafa1a52c7d.png)

**Comment by Stiofan** [comment]
Its part of the WP T&Cs that we can't install plugins outside of the wp.org repo, and there is a rule that plguins that provide external updates are not allowed on the repo, so that is why WPEU is a manual install only.  In regards to this section i just added it and we will be improving it soon. Thanks for the feedback
