### ISSUE TITLE
Missing shortcodes in ClassicPress on install

### ISSUE THREAD

**Issue by citrika** [AyeCode/geodirectory#2723]
The shortcodes are not included in pages when installing in ClassicPress.

**Comment by kprajapatii** [comment]
@citrika We have made some changes to add support GeoDirectory with ClassicPress . It will be available in next update of GeoDirectory. Meantime you can try this patch https://github.com/AyeCode/geodirectory/commit/f01054d1ce690e602fdbf766a75cdba9d60b47ca#diff-dfde70019bd2e98c71b4ab23aa63c8aa6567f2523e36b5f442e17c7aaf6a19af

For new install it will create page templates with shortcodes instead of blocks. But for existing site, the pages already created with blocks, so in this case page templates needs to modified to replace blocks with shortcodes.

Default page content with shortcodes available at GeoDirectory > Settings > General > Pages > (Specific Page) > Actions > View Default Content.

Let us know if you have a query,
