### ISSUE TITLE
Fresh install with map api on automatic or google - default location will always be philadelphia

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#413]
It is not possible to change the default location on setting "automatic" or Google API if the google api key is not setup completely with billing. 

The geocode for lookup of the location during the setup wizard will fail , request denied by google.

Should it be possible to set the default location with OSM during the setup wizard?

It looks like the default location can be changed with OSM in the normal default location settings once OSM has beeen selected.

**Comment by Stiofan** [comment]
I have set it so that if no Google api key is set then it will use OSM, there are also several warning that will show in the setup wizard if there is no key and google is set or if there are key authentication problems.

There is a different bug that exists here, i will open a new issue in LMv2
https://github.com/AyeCode/geodir_location_manager-v2/issues/32
