### ISSUE TITLE
Fresh install without default location with location manager

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#417]
It is possible for a new user with a fresh install to:

1. Leave setting "Automatic" for maps api
2. Fail to obtain google api key
3. Fail to set default location during setup wizard (will not set if no key)
4. Install location manager
5. Location manager will not have default location also

Recommendation: 

1) At some point the user should receive some warning during the setup wizard.
2) if there is not api key for google and the map api is set to automatic then osm should load to allow the user to set their default location
3) ideally the user should not be allowed to install the location manager if the default location is not yet set.
4) loading the location manager page without a default location should show an error with a direction to tell the user to set a default location

Default location tab:
The Default location tab disappears once location manager is installed. Is it possible that the default location tab could simply stay where it is, so it is always in the same place and we can always direct users there to set the default location?

What if the "Locations Tab" was always present, and contained a subtab for Default location, so these items were always near to each other. Then when Location Manager is installed, the Default location tab could simply contain some different information like a link to the Manage Location tab and tell the user to adjust the default location using the City tab instead.

![screenshot 2018-08-17 at 2 31 20 pm](https://user-images.githubusercontent.com/114659/44266272-3bc6a380-a22a-11e8-96b6-8650c8cabc6b.png)

Reported:
https://wpgeodirectory.com/support/topic/several-issues-3/#post-442755

**Comment by pol76** [comment]
+1 this is an open door for troubles. If we do as Alex suggest we will have a lot less support requests. I think the wizard shouldn't allow to skip creating a key and especially setting the default location. 

For the 1st case we could show an alert saying:

Because you skipped creating an api key for google maps the system set OSM as your default maps. 

For the second case:

Because you skipped creating a default location the system assigned a random city as default location, you can change it anytime by going here...

I think it would be better than allowing them to continue with empty fields...

**Comment by Stiofan** [comment]
I'm going to close this, if u can replicate number 1 then let me know and i'll re-open it.
