### ISSUE TITLE
GDV2 causes Ninja Forms - Form settings (X) button to become inoperative

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#469]
On a fresh install with ninja forms, button works.

Add GDV2, go to Ninja forms, choose form to edit.  See the X in upper right corner can no longer be used to close the settings.

https://ppldb.com/v2/wp-admin/admin.php?page=ninja-forms&form_id=2

![screenshot 2018-09-28 at 3 29 56 pm](https://user-images.githubusercontent.com/114659/46211269-69c3fb00-c333-11e8-9307-1f665ab82132.png)

Reporting topic

https://wpgeodirectory.com/support/topic/ninja-no-good/#post-447961

**Comment by Stiofan** [comment]
This is due to the way Font Awesome is used, we use the JS way (which saves time and resources) but if people use the old way and add classes to the <a> tags then any JS actions on those will be lost, like the X on the NF page.

This is a WP problem with Font Awesome v5, its only going to get worse, the only way is education of WP devs.

**Comment by alexrollin** [comment]
I actually opened a ticket with Ninja forms. an you write that in a way that I can send to them?
