### ISSUE TITLE
Import won't update non-standard post_status

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/geodirectory#611]
Import 10 listings with post status "published" (should be "publish").

Listings will not be visible in Backend -> All list because this is non-standard post_status

Edit CSV, change post_status to "publish" (standard)
Import
Listing post_status will not change

The only remedy is manually changing post_status in db in wp posts table.
Change in gd cpt table has no effect.

**Comment by kprajapatii** [comment]
Fixed https://github.com/AyeCode/geodirectory/commit/dcd99d76504c4607c94a4768df8915d1c40c6373

- Import 10 listings with post status "published" (should be "publish").
< Fixed

- Listings will not be visible in Backend -> All list because this is non-standard post_status
< If will set post status to 'pending' for non-standard post_status

- Edit CSV, change post_status to "publish" (standard)
Import
Listing post_status will not change
< Can't replicate this. I successfully changed post status from 'published' to 'publish' with re-import.

@alexrollin

**Comment by Stiofan** [comment]
Alex, the latest is on v2, can u please test and confirm this is working as it should

**Comment by alexrollin** [comment]
I imported 30 new listings with status published and they were changed to publish on import
magic!


[older file import, newer file with IDs is export.zip](https://github.com/AyeCode/geodirectory/files/2989966/older.file.import.newer.file.with.IDs.is.export.zip)
